#!/bin/bash

running_check=`ps -aef | grep "python [o]bplayer.py" | wc -l`

if [ "$running_check" -ge "1" ]
then
	echo OpenBroadcaster Player already running.
	exit;
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

if [ ! -x "/usr/bin/python3" ] || ! python3 -c "import apsw"
then
	echo "Switching to legacy OpenBroadcaster Player"
	git checkout legacy
	exit;
fi

python3 obplayer.py $@
