#!/bin/bash

running_check=`ps -aef | grep "python [o]bplayer.py" | wc -l`

if [ "$running_check" -ge "1" ]
then
	echo OpenBroadcaster Player already running.
	exit;
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

python obplayer.py $@
